apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: apps
spec:
  components:
  - name: apps
    type: kustomize
    properties:
      repoType: git
      url: https://github.com/zxhzx/test-vela.git
      pullInterval: 1m
      git:
        branch: master
      path: ./apps
