apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  labels:
    app: app-h5
  name: my-app
  namespace: default
spec:
  components:
    - name: my-server
      type: webservice
      properties:
        image: registry.cn-shanghai.aliyuncs.com/yogoops/testkubevela:v1.0.0-h5-dev
        ports: 
          - port: 80
            name: http
            protocol: "TCP"
            expose: true
        exposeType: "ClusterIP"