apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  labels:
    app: app-h5
  name: my-app
  namespace: default
spec:
  components:
    - name: my-server
      type: webservice
      properties:
        image: registry.cn-shanghai.aliyuncs.com/yogoops/testkubevela:v1.0.0-h5-dev
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
      traits:
        - type: ClusterIP
          ports:
          - name: http
            port: 80
            protocol: TCP
            targetPort: 80
          selector:
            app: my-app